name: Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.9"] # just test earliest and latest claimed compatibility
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Use GoLang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade wheel
          pip install mypy jsbeautifier
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check format
        if: matrix.python-version == '3.9'
        run: |
          pip install black
          black --check .
      - name: Test with unittest
        run: |
          python -m unittest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade wheel
        pip install twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Publish
      if: github.event_name == 'push'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
      continue-on-error: true
